setblock ~ ~ ~ cobblestone
setblock ~1 ~ ~ cobblestone
setblock ~1 ~ ~1 cobblestone
setblock ~ ~ ~1 cobblestone
setblock ~-1 ~ ~ cobblestone
setblock ~-1 ~ ~1 cobblestone
setblock ~-1 ~ ~-1 cobblestone
setblock ~1 ~ ~-1 cobblestone
setblock ~ ~ ~-1 cobblestone
setblock ~1 ~1 ~ cobblestone
setblock ~1 ~1 ~1 cobblestone
setblock ~ ~1 ~1 cobblestone
setblock ~-1 ~1 ~ cobblestone
setblock ~-1 ~1 ~1 cobblestone
setblock ~-1 ~1 ~-1 cobblestone
setblock ~1 ~1 ~-1 cobblestone
setblock ~ ~1 ~-1 cobblestone
setblock ~ ~1 ~ torch
setblock ~1 ~2 ~ cobblestone
setblock ~1 ~2 ~1 cobblestone
setblock ~ ~2 ~1 cobblestone
setblock ~-1 ~2 ~ cobblestone
setblock ~-1 ~2 ~1 cobblestone
setblock ~-1 ~2 ~-1 cobblestone
setblock ~1 ~2 ~-1 cobblestone
setblock ~ ~2 ~-1 cobblestone
